# **TUGAS PANDAS 2026** 🐼

---
**Nama:**  Sheyla Natasha Rahma Ditia
**NIM:**  245150401111016

Notebook ini berisi penugasan **Pandas** sebagai latihan lanjutan setelah workshop.

### Aturan singkat
- Kerjakan mandiri.
- Gunakan **Pandas** sebagai alat utama.
- Untuk feature engineering sederhana, kamu boleh menggunakan **NumPy** sebagai pendukung.
- Tulis jawaban langsung di cell yang sudah disediakan.

## **📦 Import Library & Load Dataset**

Dataset yang digunakan adalah **`taxis.csv`**.

Sumber dataset:  
`https://raw.githubusercontent.com/mwaskom/seaborn-data/master/taxis.csv`

In [3]:
pip install pandas

Requirement already satisfied: pandas in c:\users\sheyla\appdata\local\programs\python\python313\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sheyla\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sheyla\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\sheyla\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\sheyla\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/taxis.csv"
df = pd.read_csv(url)

df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

## **📌 Soal 1: Kenali Dataset Terlebih Dahulu**

Tampilkan informasi berikut dari dataset `df`:
1. 5 baris teratas
2. Shape dataset
3. Nama semua kolom
4. Informasi detail data dengan `info()`
5. Jumlah missing value per kolom

**Tujuan soal:** membiasakan diri membaca struktur dataset sebelum mulai analisis.

In [5]:
# Tulis jawabanmu di sini
df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [6]:
df.shape

(6433, 14)

In [7]:
list(df.columns)

['pickup',
 'dropoff',
 'passengers',
 'distance',
 'fare',
 'tip',
 'tolls',
 'total',
 'color',
 'payment',
 'pickup_zone',
 'dropoff_zone',
 'pickup_borough',
 'dropoff_borough']

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   str
 1   dropoff          6433 non-null   str
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   str
 9   payment          6389 non-null   str
 10  pickup_zone      6407 non-null   str
 11  dropoff_zone     6388 non-null   str
 12  pickup_borough   6407 non-null   str
 13  dropoff_borough  6388 non-null   str
dtypes: float64(5), int64(1), str(8)
memory usage: 703.7 KB

In [9]:
df.isna().sum()

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

## **📌 Soal 2: Ubah Kolom Waktu & Buat Fitur Durasi**

Kolom `pickup` dan `dropoff` masih bertipe string.  
Ubahlah keduanya menjadi datetime, lalu buat kolom baru bernama `trip_duration_min` yang berisi durasi perjalanan dalam **menit**.

Setelah itu:
1. tampilkan 5 baris pertama dari kolom `pickup`, `dropoff`, dan `trip_duration_min`
2. tampilkan rata-rata durasi perjalanan

In [10]:
# Tulis jawabanmu di sini
df["pickup"] = pd.to_datetime(df["pickup"])
df["dropoff"] = pd.to_datetime(df["dropoff"])
df["trip_duration_min"] = (df["dropoff"]-df["pickup"]).dt.total_seconds() / 60

In [11]:
df[["pickup","dropoff","trip_duration_min"]].head()

               pickup             dropoff  trip_duration_min
0 2019-03-23 20:21:09 2019-03-23 20:27:24           6.250000
1 2019-03-04 16:11:55 2019-03-04 16:19:00           7.083333
2 2019-03-27 17:53:01 2019-03-27 18:00:25           7.400000
3 2019-03-10 01:23:59 2019-03-10 01:49:51          25.866667
4 2019-03-30 13:27:42 2019-03-30 13:37:14           9.533333

In [12]:
print(df["trip_duration_min"].mean())

14.349616560443545

## **📌 Soal 3: Seleksi Data dengan `loc`, `iloc`, dan Boolean Mask**

Kerjakan hal berikut:
1. Ambil kolom `fare`, `tip`, dan `total` untuk 10 baris pertama menggunakan `.loc`
2. Ambil 5 baris pertama dan 4 kolom pertama menggunakan `.iloc`
3. Tampilkan semua trip dengan:
   - `payment == "cash"`
   - `distance > 3`
   - `tip == 0`

Tampilkan 10 baris pertama dari hasil filter pada poin (3).

In [13]:
# Tulis jawabanmu di sini
df.loc[:9,["fare","tip","total"]]

   fare   tip  total
0   7.0  2.15  12.95
1   5.0  0.00   9.30
2   7.5  2.36  14.16
3  27.0  6.15  36.95
4   9.0  1.10  13.40
5   7.5  2.16  12.96
6  13.0  2.00  18.80
7   8.5  0.00  11.80
8  15.0  1.00  19.30
9   8.0  1.00  13.30

In [14]:
df.iloc[:5,:4]

               pickup             dropoff  passengers  distance
0 2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60
1 2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79
2 2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37
3 2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70
4 2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16

In [15]:
df[(df["payment"] == "cash") & (df["distance"]>3) & (df["tip"]==0)].head(10)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,trip_duration_min
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.0,0.0,0.00,17.80,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens,20.066667
26,2019-03-03 02:45:36,2019-03-03 03:02:14,1,3.35,13.5,0.0,0.00,17.30,yellow,cash,West Chelsea/Hudson Yards,Seaport,Manhattan,Manhattan,16.633333
37,2019-03-21 18:41:58,2019-03-21 19:15:25,1,3.13,20.5,0.0,0.00,24.80,yellow,cash,Lenox Hill East,Garment District,Manhattan,Manhattan,33.450000
41,2019-03-24 18:42:56,2019-03-24 19:09:00,0,4.50,20.0,0.0,0.00,23.30,yellow,cash,TriBeCa/Civic Center,Kips Bay,Manhattan,Manhattan,26.066667
43,2019-03-27 19:39:16,2019-03-27 20:00:26,1,9.50,28.0,0.0,5.76,35.06,yellow,cash,LaGuardia Airport,Washington Heights South,Queens,Manhattan,21.166667
46,2019-03-20 11:40:59,2019-03-20 12:06:41,2,4.70,20.0,0.0,0.00,23.30,yellow,cash,Times Sq/Theatre District,Battery Park City,Manhattan,Manhattan,25.700000
49,2019-03-04 21:35:00,2019-03-04 21:53:42,1,4.87,17.5,0.0,0.00,21.30,yellow,cash,West Village,Upper West Side South,Manhattan,Manhattan,18.700000
53,2019-03-20 18:49:24,2019-03-20 19:12:40,1,13.45,36.0,0.0,0.00,37.80,yellow,cash,JFK Airport,Sunnyside,Queens,Queens,23.266667
67,2019-03-04 13:39:06,2019-03-04 13:58:52,1,3.30,15.5,0.0,0.00,18.80,yellow,cash,Garment District,Yorkville East,Manhattan,Manhattan,19.766667
75,2019-03-17 01:28:28,2019-03-17 02:04:54,1,7.95,30.0,0.0,0.00,33.80,yellow,cash,Flatiron,Jackson Heights,Manhattan,Queens,36.433333

## **📌 Soal 4: Nilai Unik & Distribusi Kategori**

Tampilkan:
1. Semua nilai unik pada kolom `payment`
2. Jumlah nilai unik pada kolom `pickup_borough`
3. Banyaknya data pada setiap kategori `payment` menggunakan `value_counts()`

Lalu jawab dengan komentar: metode pembayaran apa yang paling sering muncul?

In [16]:
# Tulis jawabanmu di sini
df["payment"].unique()

<StringArray>
['credit card', 'cash', nan]
Length: 3, dtype: str

In [17]:
df["pickup_borough"].nunique()

4

In [18]:
df["payment"].value_counts()

payment
credit card    4577
cash           1812
Name: count, dtype: int64

dari hasil value_counts kolom payment, dapat diketahui bahwa metode pembayaran yang paling sering adalah credit card

## **📌 Soal 5: Missing Value**

Kerjakan langkah berikut:
1. Tampilkan jumlah missing value per kolom
2. Buat salinan dataset bernama `df_clean`
3. Pada `df_clean`, isi missing value:
   - kolom `payment` dengan string `"unknown"`
   - kolom `dropoff_borough` dengan string `"Unknown"`
4. Tampilkan lagi jumlah missing value dari dua kolom tersebut setelah diisi

**Catatan:** gunakan `.copy()` supaya dataset asli `df` tetap aman.

In [19]:
# Tulis jawabanmu di sini
df.isna().sum()

pickup                0
dropoff               0
passengers            0
distance              0
fare                  0
tip                   0
tolls                 0
total                 0
color                 0
payment              44
pickup_zone          26
dropoff_zone         45
pickup_borough       26
dropoff_borough      45
trip_duration_min     0
dtype: int64

In [39]:
df_clean = df.copy()

In [40]:
mask = df_clean["payment"].isna()
df_clean.loc[mask, "payment"] = "unknown"

mask = df_clean["dropoff_borough"].isna()
df_clean.loc[mask, "dropoff_borough"] = "unknown"

In [41]:
df_clean.isna().sum()

pickup                0
dropoff               0
passengers            0
distance              0
fare                  0
tip                   0
tolls                 0
total                 0
color                 0
payment               0
pickup_zone          26
dropoff_zone         45
pickup_borough       26
dropoff_borough       0
trip_duration_min     0
dtype: int64

## **📌 Soal 6: Data Duplikat**

Pada dataset `taxis`, data duplikat alami jumlahnya sedikit / bahkan bisa tidak ada.  
Supaya bisa latihan, buat dataset baru bernama `df_dupes` dengan cara menambahkan **15 baris acak dari `df_clean`** ke bagian bawah dataset.

Lalu:
1. Hitung jumlah baris duplikat pada `df_dupes`
2. Buang baris duplikat tersebut dan simpan ke `df_nodup`
3. Tampilkan shape sebelum dan sesudah menghapus duplikat

In [23]:
# Tulis jawabanmu di sini
df_dupes=pd.concat([df_clean, df_clean.sample(15, random_state=42)])

In [24]:
df_dupes.shape #shape sebelum hapus duplikat

(6448, 15)

In [25]:
df_dupes.duplicated().sum()

np.int64(15)

In [26]:
df_nodup = df_dupes.drop_duplicates()

In [27]:
df_nodup.shape #shape setelah hapus duplikat

(6433, 15)

## **📌 Soal 7: Feature Engineering Sederhana**

Gunakan `df_nodup`, lalu buat:
1. Kolom `tip_pct` dengan rumus:
 
$$\text{tip_pct} = \frac{tip}{fare} \times 100$$

2. Kolom `is_long_trip`:
   - `"yes"` jika `distance >= 5`
   - `"no"` jika `distance < 5`

3. Kolom `pickup_hour` dari waktu `pickup`

Tampilkan 10 baris pertama dari kolom:
`fare`, `tip`, `tip_pct`, `distance`, `is_long_trip`, `pickup_hour`

In [30]:
# Tulis jawabanmu di sini
df_nodup["tip_pct"]=df_nodup["tip"]/df_nodup["fare"]*100
df_nodup["is_long_trip"] = np.where(df_nodup["distance"] >= 5, "yes", "no")
df_nodup["pickup_hour"] = df_nodup["pickup"].dt.hour

In [34]:
df_nodup[["fare","tip","tip_pct","distance","is_long_trip","pickup_hour"]].head(10)

   fare   tip    tip_pct  distance is_long_trip  pickup_hour
0   7.0  2.15  30.714286      1.60           no           20
1   5.0  0.00   0.000000      0.79           no           16
2   7.5  2.36  31.466667      1.37           no           17
3  27.0  6.15  22.777778      7.70          yes            1
4   9.0  1.10  12.222222      2.16           no           13
5   7.5  2.16  28.800000      0.49           no           10
6  13.0  2.00  15.384615      3.65           no           21
7   8.5  0.00   0.000000      1.40           no           12
8  15.0  1.00   6.666667      3.63           no           11
9   8.0  1.00  12.500000      1.52           no           16

In [76]:
df_nodup.groupby("is_long_trip")["tip_pct"].mean()

is_long_trip
no     17.628546
yes    12.921700
Name: tip_pct, dtype: float64

## **📌 Soal 8: GroupBy & Aggregation**

Gunakan `df_nodup`, lalu buat ringkasan per `payment` yang berisi:
1. jumlah trip
2. rata-rata `fare`
3. rata-rata `tip`
4. rata-rata `trip_duration_min`

Urutkan hasilnya berdasarkan jumlah trip dari yang terbesar ke yang terkecil.

In [38]:
# Tulis jawabanmu di sini
gbpay = df_nodup.groupby("payment")
aggregated = gbpay.agg(
    jml_trip = ("payment","count"),
    avg_fare = ("fare","mean"),
    avg_tip = ("tip", "mean"),
    avg_trip_duration = ("trip_duration_min","mean")
)
aggregated

             jml_trip   avg_fare   avg_tip  avg_trip_duration
payment
cash             1812  11.592991  0.000000          12.629323
credit card      4577  13.694750  2.781805          15.067679
unknown            44  11.988636  0.000000          10.499621

## **📌 Soal 9: GroupBy + `transform()`**

Masih menggunakan `df_nodup`, buat kolom baru bernama `fare_vs_payment_mean` dengan rumus:

\[
fare\_vs\_payment\_mean = fare - \text{rata-rata fare pada grup payment yang sama}
\]

Artinya, setiap baris dibandingkan terhadap rata-rata `fare` dari metode pembayaran yang sama.

Tampilkan 10 baris pertama dari kolom:
`payment`, `fare`, `fare_vs_payment_mean`

In [ ]:
# Tulis jawabanmu di sini
avg_fare_per_payment = df_nodup.groupby("payment")["fare"].transform("mean")
df_nodup["fare_vs_payment_mean"]=df_nodup["fare"]-avg_fare_per_payment

In [ ]:
df_nodup[["payment","fare","fare_vs_payment_mean"]].head(10)

       payment  fare  fare_vs_payment_mean
0  credit card   7.0             -6.694750
1         cash   5.0             -6.592991
2  credit card   7.5             -6.194750
3  credit card  27.0             13.305250
4  credit card   9.0             -4.694750
5  credit card   7.5             -6.194750
6  credit card  13.0             -0.694750
7      unknown   8.5             -3.488636
8  credit card  15.0              1.305250
9  credit card   8.0             -5.694750

In [70]:
df_nodup[(df_nodup["tip"]>0)&(df_nodup["payment"]=="credit card")]

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,trip_duration_min,tip_pct,is_long_trip,pickup_hour,fare_vs_payment_mean
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan,6.250000,30.714286,no,20,-6.69475
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan,7.400000,31.466667,no,17,-6.19475
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan,25.866667,22.777778,yes,1,13.30525
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan,9.533333,12.222222,no,13,-4.69475
5,2019-03-11 10:37:23,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,12.96,yellow,credit card,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan,10.133333,28.800000,no,10,-6.19475
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6414,2019-03-30 14:04:46,2019-03-30 14:18:58,2,2.60,11.0,2.91,0.0,17.46,green,credit card,Central Harlem,Yorkville West,Manhattan,Manhattan,14.200000,26.454545,no,14,-2.69475
6418,2019-03-02 21:47:50,2019-03-02 21:55:34,1,1.48,7.5,1.76,0.0,10.56,green,credit card,Forest Hills,Kew Gardens Hills,Queens,Queens,7.733333,23.466667,no,21,-6.19475
6426,2019-03-28 08:04:47,2019-03-28 08:07:46,1,0.71,4.5,0.50,0.0,5.80,green,credit card,Central Park,Upper West Side North,Manhattan,Manhattan,2.983333,11.111111,no,8,-9.19475
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan,3.566667,23.555556,no,9,-9.19475
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn,16.666667,22.400000,no,19,1.30525

## **📌 Soal 10: Sorting & Menyimpan Hasil**

Buat dataset akhir bernama `final_df` dari `df_nodup` dengan langkah:
1. Urutkan berdasarkan `total` dari terbesar ke terkecil
2. Jika nilai `total` sama, urutkan `trip_duration_min` dari terkecil ke terbesar
3. Simpan hasilnya ke file bernama **`taxis_final.csv`**

Tampilkan 10 baris pertama dari `final_df`.

In [50]:
# Tulis jawabanmu di sini
final_df = df_nodup.copy()

In [53]:
final_df.sort_values(by=["total","trip_duration_min"], ascending=[False,True], inplace=True)
final_df.head(10)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,trip_duration_min,tip_pct,is_long_trip,pickup_hour,fare_vs_payment_mean
5364,2019-03-17 16:59:17,2019-03-17 18:04:08,2,36.70,150.0,0.00,24.02,174.82,yellow,cash,JFK Airport,JFK Airport,Queens,Queens,64.850000,0.000000,yes,16,138.407009
5648,2019-03-19 14:21:35,2019-03-19 15:51:28,2,33.46,150.0,0.00,18.90,169.70,green,cash,East Flushing,NaN,Queens,unknown,89.883333,0.000000,yes,14,138.407009
622,2019-03-12 19:52:36,2019-03-12 19:52:55,3,0.00,120.0,33.20,12.50,166.00,yellow,credit card,NaN,NaN,NaN,unknown,0.316667,27.666667,no,19,106.305250
4050,2019-03-13 14:05:19,2019-03-13 15:01:16,6,33.76,143.5,0.00,0.00,144.30,yellow,cash,LaGuardia Airport,NaN,Queens,unknown,55.950000,0.000000,yes,14,131.907009
2231,2019-03-11 10:17:31,2019-03-11 11:03:55,1,26.35,130.0,0.00,5.76,136.56,yellow,cash,East Harlem North,NaN,Manhattan,unknown,46.400000,0.000000,yes,10,118.407009
3644,2019-03-19 23:30:50,2019-03-19 23:32:33,2,0.00,103.0,20.65,0.00,123.95,yellow,credit card,NaN,NaN,NaN,unknown,1.716667,20.048544,no,23,89.305250
4815,2019-03-08 11:25:08,2019-03-08 11:50:30,3,10.36,100.0,20.56,0.00,123.36,yellow,credit card,TriBeCa/Civic Center,NaN,Manhattan,unknown,25.366667,20.560000,yes,11,86.305250
4219,2019-03-08 20:07:54,2019-03-08 21:10:00,1,36.66,96.5,10.00,5.76,113.56,yellow,credit card,JFK Airport,NaN,Queens,unknown,62.100000,10.362694,yes,20,82.805250
3500,2019-03-11 17:18:03,2019-03-11 18:27:48,1,24.63,87.5,17.86,0.00,107.16,yellow,credit card,LaGuardia Airport,NaN,Queens,unknown,69.750000,20.411429,yes,17,73.805250
4218,2019-03-29 17:32:20,2019-03-29 18:53:52,1,26.92,75.5,23.19,0.00,100.49,yellow,credit card,JFK Airport,Cobble Hill,Queens,Brooklyn,81.533333,30.715232,yes,17,61.805250

In [54]:
final_df.to_csv("taxis_final.csv", index=False)
print("File tersimpan: coffee_sales.csv")

File tersimpan: coffee_sales.csv

## **🌟 Bonus (Opsional): Analisis Singkat**

Pilih **satu** insight sederhana dari dataset ini, lalu tulis dalam markdown/cell komentar.  
Contoh:
- payment apa yang paling sering dipakai?
- borough mana yang paling sering jadi titik pickup?
- apakah trip yang lebih jauh selalu menghasilkan tip lebih besar?

Tidak perlu panjang, cukup 2–4 kalimat.

Walau pada perjalanan panjang tip yang diberikan lebih besar, tetapi persentasi tip untuk perjalanan pendek lebih tinggi.

# **🎯 Penutup**

Kalau kamu sudah menyelesaikan semua soal:
- cek lagi hasil outputmu,
- pastikan bentuk array dan logikanya sesuai,
- lalu simpan notebook ini sebelum dikumpulkan.

Semangat! 🚀